# Generated by Django 4.2.30 on 2026-10-07 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_ensure_customuser_permission_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='can_paste_payments',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='can_verify_payments',
        ),
    ]
