# Generated by Django 4.2.30 on 2026-08-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(max_length=50, unique=True)),
                ('tenant_name', models.CharField(blank=True, max_length=255)),
                ('tenant_phone', models.CharField(blank=True, max_length=30)),
                ('monthly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
