import os
from django.conf import settings
from django.http import HttpResponse, Http404
from django.views.static import serve


def spa_view(request, *args, **kwargs):
    """
    Serves the React frontend index.html for all frontend routes.
    """
    index_file = settings.BASE_DIR / 'frontend' / 'dist' / 'index.html'
    if not index_file.exists():
        return HttpResponse(
            "<h3>Frontend build not found.</h3><p>Please build the frontend using <code>npm run build</code> in the frontend directory.</p>",
            status=404,
            content_type='text/html',
        )
    with open(index_file, 'r', encoding='utf-8') as f:
        return HttpResponse(f.read(), content_type='text/html')


def serve_assets(request, path):
    """
    Serves static JS/CSS assets generated by Vite in frontend/dist/assets/.
    """
    assets_dir = settings.BASE_DIR / 'frontend' / 'dist' / 'assets'
    return serve(request, path, document_root=str(assets_dir))


def serve_frontend_file(request, path):
    """
    Serves static root files like favicon.svg, icons.svg from frontend/dist/.
    """
    dist_dir = settings.BASE_DIR / 'frontend' / 'dist'
    return serve(request, path, document_root=str(dist_dir))
