# Generated by Django 4.2.30 on 2026-08-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('manual', 'Manual Review'), ('manager_reviewed', 'Manager reviewed')], default='pending', max_length=30),
        ),
    ]
