# Generated by Django 4.2.30 on 2026-08-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlogentry',
            name='payment_status',
            field=models.CharField(choices=[('full', 'Full Payment'), ('partial', 'Partial Payment'), ('overpayment', 'Over Payment'), ('unpaid', 'Not Paid')], default='partial', max_length=20),
        ),
    ]
