# Generated by Django 4.2.30 on 2026-08-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterlog', '0003_masterlogentry_confirmation_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlogentry',
            name='payment_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
