# Generated by Django 4.2.30 on 2026-08-07 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_tag', models.CharField(max_length=50)),
                ('confirmed_by', models.CharField(blank=True, max_length=100)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='payments.rawpayment')),
            ],
        ),
    ]
