# Generated by Django 4.2.30 on 2026-08-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirmations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='Confirmation_unit',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
