# Generated by Django 4.2.30 on 2026-08-07 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confirmations', '0002_confirmation_confirmation_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmation',
            name='Confirmation_unit',
        ),
    ]
