# Generated by Django 4.2.30 on 2026-08-07 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
        ('confirmations', '0003_remove_confirmation_confirmation_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='payment_status',
            field=models.CharField(choices=[('full', 'Full Payment'), ('partial', 'Partial Payment'), ('overpayment', 'Over Payment'), ('unpaid', 'Not Paid')], default='partial', max_length=20),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='selected_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmations', to='units.unit'),
        ),
    ]
