# Generated by Django 4.2.30 on 2026-08-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirmations', '0004_confirmation_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='confirmation_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='payment_month',
            field=models.CharField(blank=True, choices=[('', 'Select month'), ('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=20),
        ),
    ]
