# Generated by Django 4.2.30 on 2026-08-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirmations', '0005_confirmation_confirmation_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='payment_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='verified_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
