# Generated by Django 4.2.30 on 2026-08-14 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
        ('confirmations', '0006_confirmation_payment_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allocation_tag', models.CharField(choices=[('full', 'Full'), ('part', 'Part'), ('bal', 'Bal')], default='part', max_length=10)),
                ('payment_month', models.CharField(blank=True, choices=[('', 'Select month'), ('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=20)),
                ('payment_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('confirmation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='confirmations.confirmation')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_allocations', to='units.unit')),
            ],
        ),
    ]
